/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { BrowserRouter as Router } from "react-router-dom";
import Header from "./Header";

jest.mock("framer-motion", () => ({
  motion: {
    header: ({ children, ...props }) => <header {...props}>{children}</header>,
    img: ({ children, ...props }) => <img {...props}>{children}</img>,
    div: ({ children, ...props }) => <div {...props}>{children}</div>,
    button: ({ children, ...props }) => <button {...props}>{children}</button>,
  },
  useAnimation: () => ({
    start: jest.fn(),
  }),
}));

describe("Header", () => {
  it("renders the logo", () => {
    render(
      <Router>
        <Header />
      </Router>
    );
    const logo = screen.getByAltText("DMHedges Logo");
    expect(logo).toBeInTheDocument();
  });

  it("renders navigation links", () => {
    render(
      <Router>
        <Header />
      </Router>
    );
    const navItems = ["Home", "Shop", "Services", "Blog", "Contact"];
    navItems.forEach((item) => {
      const link = screen.getByText(item);
      expect(link).toBeInTheDocument();
    });
  });

  it("renders search input", () => {
    render(
      <Router>
        <Header />
      </Router>
    );
    const searchInput = screen.getByPlaceholderText("Search...");
    expect(searchInput).toBeInTheDocument();
  });

  it("renders cart icon", () => {
    render(
      <Router>
        <Header />
      </Router>
    );
    const cartIcon = screen.getByRole("link", { name: /cart/i });
    expect(cartIcon).toBeInTheDocument();
  });
});
