/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const AboutUsSummary = () => {
  return (
    <section className="py-12 bg-green-50">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center"
        >
          <h2 className="text-3xl font-bold mb-6">About DMHedges</h2>
          <p className="text-lg mb-8 max-w-2xl mx-auto">
            At DMHedges, we're passionate about creating beautiful, sustainable
            gardens. With over 20 years of experience, our team of expert
            gardeners is dedicated to transforming outdoor spaces into lush,
            vibrant havens.
          </p>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-6 rounded-full transition duration-300"
          >
            Learn More About Us
          </motion.button>
        </motion.div>
      </div>
    </section>
  );
};

export default AboutUsSummary;
