/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import HeroSection from "./HeroSection";
import FeaturedProducts from "./FeaturedProducts";
import AboutUsSummary from "./AboutUsSummary";
import LatestBlogPosts from "./LatestBlogPosts";
import CustomerTestimonials from "./CustomerTestimonials";
import NewsletterSignup from "./NewsletterSignup";

const HomePage = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
      className="flex flex-col min-h-screen"
    >
      {/* <header className="bg-green-800 text-white p-4">
        <nav>
          <ul className="flex justify-around">
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#home">Home</a>
            </motion.li>
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#products">Products</a>
            </motion.li>
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#about">About</a>
            </motion.li>
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#contact">Contact</a>
            </motion.li>
          </ul>
        </nav>
      </header> */}

      <main className="flex-grow">
        <HeroSection />
        <FeaturedProducts />
        <AboutUsSummary />
        <LatestBlogPosts />
        <CustomerTestimonials />
        <NewsletterSignup />
      </main>

      <footer className="bg-green-800 text-white p-4 mt-8">
        <div className="container mx-auto text-center">
          <p>&copy; 2023 DMHedges Gardening. All rights reserved.</p>
        </div>
      </footer>
    </motion.div>
  );
};

export default HomePage;
