/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import HomePage from './HomePage';

jest.mock('./HeroSection', () => () => <div data-testid="hero-section" />);
jest.