/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const blogPosts = [
  {
    id: 1,
    title: "10 Tips for a Thriving Summer Garden",
    excerpt:
      "Learn how to keep your garden blooming all summer long with these expert tips.",
    image: "/summer-garden.jpg",
  },
  {
    id: 2,
    title: "The Benefits of Organic Gardening",
    excerpt:
      "Discover why organic gardening is better for your plants, your health, and the environment.",
    image: "/organic-gardening.jpg",
  },
  {
    id: 3,
    title: "Creating a Water-Efficient Garden",
    excerpt:
      "Explore techniques for conserving water while maintaining a beautiful garden.",
    image: "/water-efficient-garden.jpg",
  },
];

const LatestBlogPosts = () => {
  return (
    <section className="py-12 bg-white">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-8">
          Latest Blog Posts
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {blogPosts.map((post, index) => (
            <motion.article
              key={post.id}
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1, duration: 0.5 }}
              whileHover={{ scale: 1.03 }}
              className="bg-gray-100 rounded-lg overflow-hidden shadow-md"
            >
              <img
                src={post.image}
                alt={post.title}
                className="w-full h-48 object-cover"
              />
              <div className="p-6">
                <h3 className="text-xl font-semibold mb-2">{post.title}</h3>
                <p className="text-gray-600 mb-4">{post.excerpt}</p>
                <motion.a
                  href="#"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="text-green-600 font-semibold hover:text-green-700 transition duration-300"
                >
                  Read More →
                </motion.a>
              </div>
            </motion.article>
          ))}
        </div>
      </div>
    </section>
  );
};

export default LatestBlogPosts;
