/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const NewsletterSignup = () => {
  return (
    <section className="py-12 bg-green-600 text-white">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center"
        >
          <h2 className="text-3xl font-bold mb-4">
            Stay Connected with DMHedges
          </h2>
          <p className="text-xl mb-8">
            Sign up for our newsletter to receive gardening tips, special
            offers, and more!
          </p>
          <form className="max-w-md mx-auto">
            <div className="flex flex-col sm:flex-row gap-4">
              <motion.input
                whileFocus={{ scale: 1.05 }}
                type="email"
                placeholder="Enter your email"
                className="flex-grow py-2 px-4 rounded-full text-gray-900"
                required
              />
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                type="submit"
                className="bg-white text-green-600 font-bold py-2 px-6 rounded-full hover:bg-green-100 transition duration-300"
              >
                Subscribe
              </motion.button>
            </div>
          </form>
        </motion.div>
      </div>
    </section>
  );
};

export default NewsletterSignup;
