/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const pricingTiers = [
  {
    name: "Basic",
    price: "$99",
    features: [
      "Weekly lawn mowing",
      "Seasonal clean-up",
      "Basic pruning",
      "Fertilization (2x per year)",
    ],
  },
  {
    name: "Standard",
    price: "$199",
    features: [
      "All Basic features",
      "Bi-weekly garden bed maintenance",
      "Pest control",
      "Irrigation system check-ups",
    ],
  },
  {
    name: "Premium",
    price: "$299",
    features: [
      "All Standard features",
      "Custom landscape design consultation",
      "Monthly flower rotations",
      "Priority scheduling",
    ],
  },
];

const PricingInformation = () => {
  return (
    <section className="mb-12">
      <h2 className="text-3xl font-semibold mb-6 text-center">
        Pricing Information
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {pricingTiers.map((tier, index) => (
          <motion.div
            key={tier.name}
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="bg-white p-6 rounded-lg shadow-md"
          >
            <h3 className="text-2xl font-semibold mb-4 text-center">
              {tier.name}
            </h3>
            <p className="text-4xl font-bold text-center text-green-600 mb-6">
              {tier.price}
              <span className="text-sm text-gray-600">/month</span>
            </p>
            <ul className="mb-6">
              {tier.features.map((feature, featureIndex) => (
                <motion.li
                  key={featureIndex}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 + featureIndex * 0.1 }}
                  className="flex items-center mb-2"
                >
                  <svg
                    className="w-4 h-4 mr-2 text-green-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  {feature}
                </motion.li>
              ))}
            </ul>
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="w-full bg-green-600 text-white px-6 py-2 rounded-full hover:bg-green-700 transition duration-300"
            >
              Choose Plan
            </motion.button>
          </motion.div>
        ))}
      </div>
      <p className="text-center mt-8 text-gray-600">
        * Prices may vary based on the size and complexity of your property.
        Contact us for a personalized quote.
      </p>
    </section>
  );
};

export default PricingInformation;
