/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const RequestQuoteCTA = () => {
  return (
    <section className="mb-12">
      <motion.div
        initial={{ opacity: 0, y: 50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="bg-green-600 text-white p-8 rounded-lg shadow-lg text-center"
      >
        <h2 className="text-3xl font-semibold mb-4">
          Ready to Transform Your Outdoor Space?
        </h2>
        <p className="text-xl mb-6">
          Get a personalized quote for your gardening needs today!
        </p>
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          className="bg-white text-green-600 px-8 py-3 rounded-full text-lg font-semibold hover:bg-green-100 transition duration-300"
        >
          Request a Quote
        </motion.button>
      </motion.div>
    </section>
  );
};

export default RequestQuoteCTA;
