/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const services = [
  {
    title: "Landscape Design",
    description:
      "Create your dream outdoor space with our expert landscape design services.",
    icon: "🏞️",
  },
  {
    title: "Garden Maintenance",
    description:
      "Keep your garden looking beautiful year-round with our professional maintenance services.",
    icon: "🌿",
  },
  {
    title: "Irrigation Systems",
    description:
      "Efficient watering solutions to keep your plants healthy and your water bills low.",
    icon: "💧",
  },
  {
    title: "Hardscaping",
    description:
      "Enhance your outdoor living with custom patios, walkways, and retaining walls.",
    icon: "🧱",
  },
];

const ServiceOverview = () => {
  return (
    <section className="mb-12">
      <h2 className="text-3xl font-semibold mb-6">Our Services</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {services.map((service, index) => (
          <motion.div
            key={service.title}
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            whileHover={{ scale: 1.05 }}
            className="bg-white p-6 rounded-lg shadow-md"
          >
            <div className="text-4xl mb-4">{service.icon}</div>
            <h3 className="text-xl font-semibold mb-2">{service.title}</h3>
            <p className="text-gray-600">{service.description}</p>
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default ServiceOverview;
