/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import ServiceOverview from "./ServiceOverview";
import IndividualServiceSections from "./IndividualServiceSections";
import PricingInformation from "./PricingInformation";
import RequestQuoteCTA from "./RequestQuoteCTA";

const ServicesPage = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
      className="min-h-screen bg-green-50"
    >
      <header className="bg-green-800 text-white p-4">
        <nav>
          <ul className="flex justify-around">
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#home">Home</a>
            </motion.li>
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#services">Services</a>
            </motion.li>
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#about">About</a>
            </motion.li>
            <motion.li whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <a href="#contact">Contact</a>
            </motion.li>
          </ul>
        </nav>
      </header>

      <main className="container mx-auto px-4 py-8">
        <h1 className="text-4xl font-bold text-center mb-8">Our Services</h1>
        <ServiceOverview />
        <IndividualServiceSections />
        <PricingInformation />
        <RequestQuoteCTA />
      </main>

      <footer className="bg-green-800 text-white p-4 mt-8">
        <div className="container mx-auto text-center">
          <p>&copy; 2023 DMHedges Gardening. All rights reserved.</p>
        </div>
      </footer>
    </motion.div>
  );
};

export default ServicesPage;
