/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const RatingSummary = ({ overallRating }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-white rounded-lg shadow-md p-6 mb-8"
    >
      <h2 className="text-2xl font-semibold text-green-800 mb-4">
        Overall Rating
      </h2>
      <div className="flex items-center">
        <div className="text-4xl font-bold text-green-600 mr-4">
          {overallRating.toFixed(1)}
        </div>
        <div className="flex">
          {[...Array(5)].map((_, i) => (
            <motion.svg
              key={i}
              className={`w-8 h-8 ${
                i < Math.round(overallRating)
                  ? "text-yellow-400"
                  : "text-gray-300"
              }`}
              fill="currentColor"
              viewBox="0 0 20 20"
              initial={{ opacity: 0, scale: 0 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.2 + i * 0.1 }}
            >
              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
            </motion.svg>
          ))}
        </div>
      </div>
    </motion.div>
  );
};

export default RatingSummary;
