/**
 * This code was generated by Builder.io.
 */
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import SearchBar from './SearchBar';
import FAQItem from './FAQItem';

const FAQPage = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [faqs, setFaqs] = useState([
    {
      question: 'What types of plants are best for beginners?',
      answer: 'Some great plants for beginners include succulents, pothos, snake plants, and spider plants. These are low-maintenance and can tolerate various light conditions.',
      category: 'Plants'
    },
    {
      question: 'How often should I water my plants?',
      answer: "Watering frequency depends on the plant type, pot size, and environmental conditions. Generally, it's best to water when the top inch of soil feels dry. Always check the specific care instructions for your plant.",
      category: 'Care'
    },
    {
      question: "What's the best fertilizer for vegetable gardens?",
      answer: 'A balanced, all-purpose fertilizer (like a 10-10-10 NPK ratio) works well for most vegetable gardens. Organic options include compost, fish emulsion, or aged manure.',
      category: 'Gardening'
    },
    {
      question: 'How do I get rid of common garden pests?',
      answer: 'There are various methods to control pests, including using neem oil, introducing beneficial insects, or applying diatomaceous earth. For severe infestations, consider organic pesticides or consult a professional.',
      category: 'Pests'
    },
    {
      question: "What's the best way to start a compost pile?",
      answer: 'Start with a mix of "green" (nitrogen-rich) and "brown" (carbon-rich) materials. Layer these materials, keep the pile moist, and turn it regularly. Avoid adding meat, dairy, or diseased plants to your compost.',
      category: 'Composting'
    }
  ]);

  const filteredFAQs = faqs.filter(faq =>
    faq.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
    faq.answer.toLowerCase().includes(searchTerm.toLowerCase()) ||
    faq.category.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="min-h-screen bg-green-50 py-12 px-4 sm:px-6 lg:px-8"
    >
      <div className="max-w-3xl mx-auto">
        <motion.h1
          initial={{ y: -20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.5 }}
          className="text-3xl font-extrabold text-green-800 mb-8 text-center"
        >
          Frequently Asked Questions
        </motion.h1>
        <SearchBar searchTerm={searchTerm} setSearchTerm={setSearchTerm} />
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="mt-8 space-y-4"
        >
          <AnimatePresence>
            {filteredFAQs.map((faq, index) => (
              <FAQItem key={index} faq={faq} />
            ))}
          </AnimatePresence>
        </motion.div>
      </div>
    </motion.div>
  );
};

export default FAQPage;