/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import FAQPage from "./FAQPage";

describe("FAQPage", () => {
  test("renders FAQ page with title", () => {
    render(<FAQPage />);
    const titleElement = screen.getByText(/Frequently Asked Questions/i);
    expect(titleElement).toBeInTheDocument();
  });

  test("renders search bar", () => {
    render(<FAQPage />);
    const searchInput = screen.getByPlaceholderText(/Search FAQs.../i);
    expect(searchInput).toBeInTheDocument();
  });

  test("renders FAQ items", () => {
    render(<FAQPage />);
    const faqItems = screen.getAllByRole("button");
    expect(faqItems.length).toBeGreaterThan(0);
  });

  test("filters FAQ items based on search", () => {
    render(<FAQPage />);
    const searchInput = screen.getByPlaceholderText(/Search FAQs.../i);
    fireEvent.change(searchInput, { target: { value: "water" } });
    const waterRelatedFAQ = screen.getByText(
      /How often should I water my plants?/i
    );
    expect(waterRelatedFAQ).toBeInTheDocument();
  });

  test("expands FAQ item when clicked", () => {
    render(<FAQPage />);
    const faqItem = screen.getByText(
      /What types of plants are best for beginners?/i
    );
    fireEvent.click(faqItem);
    const answer = screen.getByText(
      /Some great plants for beginners include succulents/i
    );
    expect(answer).toBeInTheDocument();
  });
});
