/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen, fireEvent } from "@testing-library/react";
import SearchBar from "./SearchBar";

describe("SearchBar", () => {
  test("renders search input", () => {
    render(<SearchBar searchTerm="" setSearchTerm={() => {}} />);
    const searchInput = screen.getByPlaceholderText(/Search FAQs.../i);
    expect(searchInput).toBeInTheDocument();
  });

  test("calls setSearchTerm when input changes", () => {
    const mockSetSearchTerm = jest.fn();
    render(<SearchBar searchTerm="" setSearchTerm={mockSetSearchTerm} />);
    const searchInput = screen.getByPlaceholderText(/Search FAQs.../i);
    fireEvent.change(searchInput, { target: { value: "test" } });
    expect(mockSetSearchTerm).toHaveBeenCalledWith("test");
  });

  test("displays search icon", () => {
    render(<SearchBar searchTerm="" setSearchTerm={() => {}} />);
    const searchIcon = screen.getByRole("img", { hidden: true });
    expect(searchIcon).toBeInTheDocument();
  });
});
