/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import PrivacyPolicy from "./PrivacyPolicy";

jest.mock("framer-motion", () => ({
  motion: {
    div: ({ children, ...props }) => <div {...props}>{children}</div>,
    h1: ({ children, ...props }) => <h1 {...props}>{children}</h1>,
    section: ({ children, ...props }) => (
      <section {...props}>{children}</section>
    ),
  },
}));

describe("PrivacyPolicy", () => {
  it("renders the privacy policy title", () => {
    render(<PrivacyPolicy />);
    expect(screen.getByText("Privacy Policy")).toBeInTheDocument();
  });

  it("renders all section headings", () => {
    render(<PrivacyPolicy />);
    expect(screen.getByText("1. Information Collection")).toBeInTheDocument();
    expect(screen.getByText("2. Use of Information")).toBeInTheDocument();
    expect(screen.getByText("3. Information Sharing")).toBeInTheDocument();
    expect(screen.getByText("4. Data Security")).toBeInTheDocument();
    expect(screen.getByText("5. Your Rights")).toBeInTheDocument();
    expect(screen.getByText("6. Changes to This Policy")).toBeInTheDocument();
    expect(screen.getByText("7. Contact Us")).toBeInTheDocument();
  });

  it("renders the contact email", () => {
    render(<PrivacyPolicy />);
    expect(screen.getByText("privacy@dmhedges.com")).toBeInTheDocument();
  });
});
