/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const PrivacyPolicy = () => {
  const fadeInUp = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.5 },
  };

  return (
    <motion.div
      className="min-h-screen bg-green-50 py-12 px-4 sm:px-6 lg:px-8"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <div className="max-w-3xl mx-auto">
        <motion.h1
          className="text-3xl font-bold text-green-800 mb-8"
          {...fadeInUp}
        >
          Privacy Policy
        </motion.h1>

        <motion.section {...fadeInUp} className="mb-8">
          <h2 className="text-2xl font-semibold text-green-700 mb-4">
            1. Information Collection
          </h2>
          <p className="text-gray-700">
            We collect information you provide directly to us, such as when you
            create an account, make a purchase, or contact us for support. This
            may include your name, email address, postal address, phone number,
            and payment information.
          </p>
        </motion.section>

        <motion.section {...fadeInUp} className="mb-8">
          <h2 className="text-2xl font-semibold text-green-700 mb-4">
            2. Use of Information
          </h2>
          <p className="text-gray-700">
            We use the information we collect to provide, maintain, and improve
            our services, to process your transactions, to send you technical
            notices and support messages, and to communicate with you about
            products, services, offers, and events.
          </p>
        </motion.section>

        <motion.section {...fadeInUp} className="mb-8">
          <h2 className="text-2xl font-semibold text-green-700 mb-4">
            3. Information Sharing
          </h2>
          <p className="text-gray-700">
            We do not share your personal information with third parties except
            as described in this policy. We may share your information with
            service providers who perform services on our behalf, or when
            required by law.
          </p>
        </motion.section>

        <motion.section {...fadeInUp} className="mb-8">
          <h2 className="text-2xl font-semibold text-green-700 mb-4">
            4. Data Security
          </h2>
          <p className="text-gray-700">
            We take reasonable measures to help protect your personal
            information from loss, theft, misuse, unauthorized access,
            disclosure, alteration, and destruction.
          </p>
        </motion.section>

        <motion.section {...fadeInUp} className="mb-8">
          <h2 className="text-2xl font-semibold text-green-700 mb-4">
            5. Your Rights
          </h2>
          <p className="text-gray-700">
            You have the right to access, correct, or delete your personal
            information. You can also object to or restrict certain processing
            of your data. To exercise these rights, please contact us using the
            information provided below.
          </p>
        </motion.section>

        <motion.section {...fadeInUp} className="mb-8">
          <h2 className="text-2xl font-semibold text-green-700 mb-4">
            6. Changes to This Policy
          </h2>
          <p className="text-gray-700">
            We may update this privacy policy from time to time. We will notify
            you of any changes by posting the new privacy policy on this page
            and updating the effective date.
          </p>
        </motion.section>

        <motion.section {...fadeInUp} className="mb-8">
          <h2 className="text-2xl font-semibold text-green-700 mb-4">
            7. Contact Us
          </h2>
          <p className="text-gray-700">
            If you have any questions about this privacy policy, please contact
            us at privacy@dmhedges.com.
          </p>
        </motion.section>
      </div>
    </motion.div>
  );
};

export default PrivacyPolicy;
