/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import TermsOfService from "./TermsOfService";

jest.mock("framer-motion", () => ({
  motion: {
    div: ({ children, ...props }) => <div {...props}>{children}</div>,
    h1: ({ children, ...props }) => <h1 {...props}>{children}</h1>,
    section: ({ children, ...props }) => (
      <section {...props}>{children}</section>
    ),
  },
}));

describe("TermsOfService", () => {
  it("renders the terms of service title", () => {
    render(<TermsOfService />);
    expect(screen.getByText("Terms of Service")).toBeInTheDocument();
  });

  it("renders all section headings", () => {
    render(<TermsOfService />);
    expect(screen.getByText("1. Acceptance of Terms")).toBeInTheDocument();
    expect(screen.getByText("2. Use of Services")).toBeInTheDocument();
    expect(screen.getByText("3. Intellectual Property")).toBeInTheDocument();
    expect(screen.getByText("4. User Accounts")).toBeInTheDocument();
    expect(screen.getByText("5. Limitation of Liability")).toBeInTheDocument();
    expect(screen.getByText("6. Governing Law")).toBeInTheDocument();
    expect(screen.getByText("7. Changes to Terms")).toBeInTheDocument();
    expect(screen.getByText("8. Contact Information")).toBeInTheDocument();
  });

  it("renders the contact email", () => {
    render(<TermsOfService />);
    expect(screen.getByText("terms@dmhedges.com")).toBeInTheDocument();
  });
});
