/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import ServicesPage from "../ServicesPage";

jest.mock("../ServiceOverview", () => () => (
  <div data-testid="service-overview">Service Overview</div>
));
jest.mock("../IndividualServiceSections", () => () => (
  <div data-testid="individual-service-sections">
    Individual Service Sections
  </div>
));
jest.mock("../PricingInformation", () => () => (
  <div data-testid="pricing-information">Pricing Information</div>
));
jest.mock("../RequestQuoteCTA", () => () => (
  <div data-testid="request-quote-cta">Request Quote CTA</div>
));

describe("ServicesPage", () => {
  it("renders all components correctly", () => {
    render(<ServicesPage />);

    expect(screen.getByText("Our Services")).toBeInTheDocument();
    expect(screen.getByTestId("service-overview")).toBeInTheDocument();
    expect(
      screen.getByTestId("individual-service-sections")
    ).toBeInTheDocument();
    expect(screen.getByTestId("pricing-information")).toBeInTheDocument();
    expect(screen.getByTestId("request-quote-cta")).toBeInTheDocument();
  });

  it("renders navigation links", () => {
    render(<ServicesPage />);

    expect(screen.getByText("Home")).toBeInTheDocument();
    expect(screen.getByText("Services")).toBeInTheDocument();
    expect(screen.getByText("About")).toBeInTheDocument();
    expect(screen.getByText("Contact")).toBeInTheDocument();
  });

  it("renders footer with copyright information", () => {
    render(<ServicesPage />);

    expect(
      screen.getByText(/© 2023 DMHedges Gardening. All rights reserved./)
    ).toBeInTheDocument();
  });
});
