/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import ServiceOverview from '../ServiceOverview';

describe('ServiceOverview', () => {
  it('renders all service cards', () => {
    render(<ServiceOverview />);

    expect(screen.getByText('Landscape Design')).toBeInTheDocument();
    expect(screen.getByText('Garden Maintenance')).toBeInTheDocument();
    expect(screen.getByText('Irrigation Systems')).toBeInTheDocument();
    expect(screen.getByText('Hardsc