/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const ContactInfo = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-white p-6 rounded-lg shadow-md mb-6"
    >
      <h2 className="text-2xl font-semibold mb-4">Contact Information</h2>
      <motion.div whileHover={{ scale: 1.05 }} className="mb-4">
        <h3 className="font-semibold">Address:</h3>
        <p>123 Garden Street, Green City, GC 12345</p>
      </motion.div>
      <motion.div whileHover={{ scale: 1.05 }} className="mb-4">
        <h3 className="font-semibold">Phone:</h3>
        <p>(555) 123-4567</p>
      </motion.div>
      <motion.div whileHover={{ scale: 1.05 }} className="mb-4">
        <h3 className="font-semibold">Email:</h3>
        <p>info@dmhedgesgardening.com</p>
      </motion.div>
      <motion.div whileHover={{ scale: 1.05 }}>
        <h3 className="font-semibold">Business Hours:</h3>
        <p>Monday - Friday: 9:00 AM - 5:00 PM</p>
        <p>Saturday: 10:00 AM - 4:00 PM</p>
        <p>Sunday: Closed</p>
      </motion.div>
    </motion.div>
  );
};

export default ContactInfo;
