/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render, screen } from "@testing-library/react";
import { BrowserRouter as Router } from "react-router-dom";
import Footer from "./Footer";

jest.mock("framer-motion", () => ({
  motion: {
    li: ({ children, ...props }) => <li {...props}>{children}</li>,
    a: ({ children, ...props }) => <a {...props}>{children}</a>,
    button: ({ children, ...props }) => <button {...props}>{children}</button>,
    div: ({ children, ...props }) => <div {...props}>{children}</div>,
  },
}));

describe("Footer", () => {
  beforeEach(() => {
    render(
      <Router>
        <Footer />
      </Router>
    );
  });

  it("renders quick links", () => {
    expect(screen.getByText("Quick Links")).toBeInTheDocument();
    expect(screen.getByText("About Us")).toBeInTheDocument();
    expect(screen.getByText("Services")).toBeInTheDocument();
    expect(screen.getByText("Blog")).toBeInTheDocument();
    expect(screen.getByText("Contact")).toBeInTheDocument();
  });

  it("renders contact information", () => {
    expect(screen.getByText("Contact Information")).toBeInTheDocument();
    expect(
      screen.getByText("123 Garden Street, Green City, GC 12345")
    ).toBeInTheDocument();
    expect(screen.getByText("Phone: (555) 123-4567")).toBeInTheDocument();
    expect(screen.getByText("Email: info@dmhedges.com")).toBeInTheDocument();
  });

  it("renders social media links", () => {
    expect(screen.getByText("Follow Us")).toBeInTheDocument();
    expect(screen.getByAltText("Facebook")).toBeInTheDocument();
    expect(screen.getByAltText("Twitter")).toBeInTheDocument();
    expect(screen.getByAltText("Instagram")).toBeInTheDocument();
    expect(screen.getByAltText("LinkedIn")).toBeInTheDocument();
  });

  it("renders newsletter signup form", () => {
    expect(screen.getByText("Newsletter Signup")).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Enter your email")).toBeInTheDocument();
    expect(screen.getByText("Subscribe")).toBeInTheDocument();
  });

  it("renders copyright and legal links", () => {
    expect(
      screen.getByText("© 2023 DMHedges. All rights reserved.")
    ).toBeInTheDocument();
    expect(screen.getByText("Privacy Policy")).toBeInTheDocument();
    expect(screen.getByText("Terms of Service")).toBeInTheDocument();
  });
});
