/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";
import CompanyOverview from "./CompanyOverview";
import OurTeam from "./OurTeam";
import OurStory from "./OurStory";
import CustomerTestimonials from "./CustomerTestimonials";
// import PressMediaMentions from "./PressMediaMentions";


const AboutUsPage = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
      className="flex flex-col min-h-screen"
    >
    
      

      <main className="flex-grow">
        <CompanyOverview />
        <OurTeam />
        <OurStory />
        <CustomerTestimonials />
        {/* <PressMediaMentions /> */}
      </main>

      {/* <footer className="bg-green-800 text-white p-4 mt-8">
        <div className="container mx-auto text-center">
          <p>&copy; 2023 DMHedges Gardening. All rights reserved.</p>
        </div>
      </footer> */}
    </motion.div>
  );
};

export default AboutUsPage;
