/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const CompanyOverview = () => {
  return (
    <motion.section
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8 }}
      className="py-12 bg-green-50"
    >
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold mb-6 text-center">
          Company Overview
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2, duration: 0.6 }}
          >
            <h3 className="text-2xl font-semibold mb-4">Our History</h3>
            <p className="text-gray-700">
              DMHedges was founded in 1995 with a passion for creating
              beautiful, sustainable gardens. Over the past 25 years, we've
              grown from a small local business to a leading name in gardening
              and landscaping services.
            </p>
          </motion.div>
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4, duration: 0.6 }}
          >
            <h3 className="text-2xl font-semibold mb-4">Mission Statement</h3>
            <p className="text-gray-700">
              Our mission is to transform outdoor spaces into thriving,
              eco-friendly environments that bring joy and harmony to our
              clients' lives while promoting sustainable gardening practices.
            </p>
          </motion.div>
        </div>
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6, duration: 0.6 }}
          className="mt-8"
        >
          <h3 className="text-2xl font-semibold mb-4">Core Values</h3>
          <ul className="list-disc list-inside text-gray-700">
            <li>
              Sustainability: We prioritize eco-friendly practices in all our
              projects.
            </li>
            <li>
              Innovation: We constantly seek new, creative solutions in
              gardening and landscaping.
            </li>
            <li>Quality: We deliver excellence in every aspect of our work.</li>
            <li>
              Customer Satisfaction: We strive to exceed our clients'
              expectations.
            </li>
            <li>
              Community: We actively contribute to and support our local
              community.
            </li>
          </ul>
        </motion.div>
      </div>
    </motion.section>
  );
};

export default CompanyOverview;
