/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const milestones = [
  { year: 1995, event: "DMHedges founded by John Doe" },
  { year: 2000, event: "Expanded services to include landscape design" },
  { year: 2005, event: "Opened our first garden center" },
  { year: 2010, event: "Launched sustainable gardening initiative" },
  { year: 2015, event: "Celebrated 20 years in business" },
  { year: 2020, event: "Introduced virtual garden consultations" },
];

const OurStory = () => {
  return (
    <section className="py-12 bg-green-100">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold mb-8 text-center">Our Story</h2>
        <div className="relative">
          {milestones.map((milestone, index) => (
            <motion.div
              key={milestone.year}
              initial={{ opacity: 0, x: index % 2 === 0 ? -50 : 50 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.2, duration: 0.6 }}
              className={`flex ${
                index % 2 === 0 ? "justify-start" : "justify-end"
              } mb-8`}
            >
              <div className="w-1/2 bg-white rounded-lg shadow-md p-4">
                <h3 className="text-xl font-semibold mb-2">{milestone.year}</h3>
                <p className="text-gray-700">{milestone.event}</p>
              </div>
            </motion.div>
          ))}
          <div className="absolute top-0 bottom-0 left-1/2 w-1 bg-green-500 transform -translate-x-1/2"></div>
        </div>
      </div>
    </section>
  );
};

export default OurStory;
