/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { motion } from "framer-motion";

const teamMembers = [
  {
    name: "John Doe",
    role: "Founder & CEO",
    image: "/john-doe.jpg",
    bio: "John has over 30 years of experience in landscaping and garden design.",
  },
  {
    name: "Jane Smith",
    role: "Head of Horticulture",
    image: "/jane-smith.jpg",
    bio: "Jane is an expert in plant biology and sustainable gardening practices.",
  },
  {
    name: "Mike Johnson",
    role: "Lead Landscape Architect",
    image: "/mike-johnson.jpg",
    bio: "Mike brings creativity and technical expertise to every project.",
  },
  {
    name: "Sarah Brown",
    role: "Customer Relations Manager",
    image: "/sarah-brown.jpg",
    bio: "Sarah ensures our clients receive top-notch service and support.",
  },
];

const OurTeam = () => {
  return (
    <section className="py-12 bg-white">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold mb-8 text-center">Our Team</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {teamMembers.map((member, index) => (
            <motion.div
              key={member.name}
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1, duration: 0.5 }}
              whileHover={{ scale: 1.05 }}
              className="bg-green-50 rounded-lg overflow-hidden shadow-md"
            >
              <img
                src={member.image}
                alt={member.name}
                className="w-full h-48 object-cover"
              />
              <div className="p-4">
                <h3 className="text-xl font-semibold mb-2">{member.name}</h3>
                <p className="text-gray-600 mb-2">{member.role}</p>
                <p className="text-gray-700">{member.bio}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default OurTeam;
