/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { motion } from 'framer-motion';

const pressMentions = [
  {
    id: 1,
    source: 'Green Living Magazine',
    title: 'DMHedges: Pioneers in Sustainable Gardening',
    date: 'May 2022',
    logo: '/green-living-logo.png',
  },
  {
    id: 2,
    source: 'Home & Garden TV',
    title: 'Featured in "Garden Transformations" series',
    date: 'July 2021',
    logo: '/hgtv-logo.png',
  },
  {
    id: 3,
    source: 'EcoWatch',
    title: 'DMHedges Wins "Green Business of the Year" Award',
    date: 'November 2020',
    logo: '/ecowatch-logo.png',
  },
  {
    id: 4,
    source: 'Local News 5',
    title: 'DMHedges Leads Community Garden Initiative',
    date: 'April 2023',
    logo: '/local-news-5-logo.png',
  },
];

const PressMediaMentions = () => {
  return (
    <section className="py-12 bg-green-50">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-8">Press & Media Mentions</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {pressMentions.map((mention, index) => (
            <motion.div
              key={mention.id}
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1, duration: 0.5 }}
              whileHover={{ scale: 1.05 }}
              className="bg-white rounded-lg shadow-md p-4 flex flex-col items-center"
            >
              <img src={mention.logo} alt={mention.source} className="w-24 h-24 object-contain mb-4" />
              <h3 className="text-lg font-semibold text-center mb-2">{mention.source}</h3>
              <p className="text-gray-700 text-center mb-2">{mention.title}</p>
              <p className="text-gray-600 text-sm">{mention.date}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>

        )}











        export default PressMediaMentions